### ISSUE TITLE
The colors, what do they mean?

### ISSUE THREAD

**Issue by August-C** [DranKof/NutView#1]
I like how everything is color-coded, but I'm not sure what the different colors mean. Would it be possible to add a legend of sorts? Thanks!

**Comment by dstults** [comment]
I just added a legend and as an added bonus: When you click on the various legend guides, it disables them so if, for instance, a specific host is all "dead" and you disable the "dead" display, it will make all dead hosts not display. If you only want to see hosts with newly opened ports (or, like when a host first comes online and all the ports are new), then disable all states except "new".

Before:
![image](https://user-images.githubusercontent.com/20900852/74971291-b4389280-53d4-11ea-93e4-9aa9d83c8389.png)

No Dead:
![image](https://user-images.githubusercontent.com/20900852/74971320-c31f4500-53d4-11ea-8809-2294f32ff4ee.png)

New Only:
![image](https://user-images.githubusercontent.com/20900852/74971257-a3881c80-53d4-11ea-8fe9-cae20055a559.png)
